name: Deploy to dev environment
on:
  workflow_dispatch:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
env:
  IMAGE_TAG: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    environment: development
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main

      - name: Build Docker image
        run: docker build -t $IMAGE_TAG -f Dockerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to ghcr
        run: docker push $IMAGE_TAG
